# generate pubkey: cat /to/path/id_ed25519 | ssh-keygen -y -f /dev/stdin | ssh-to-age
# generage prikey: cat /to/path/id_ed25519 | ssh-to-age -private-key > ~/.config/sops/age/keys.txt

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    age: age1sqw56f8lpktsrrk2yax57ntj6gm99mla5fs5dl0lp73240606gyqcq3yrq

